tp5/config/routes.rb
#root to: 'pets#index'

Rails.application.routes.draw do
  root to: 'pets#index'
  resources :pets
  resources :breeds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

tp5/app/models/breed.rb
class Breed < ApplicationRecord
end

tp5/app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :breed
end

tp5/app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  before_action :set_breed, only: [:show, :edit, :update, :destroy]

  # GET /breeds
  # GET /breeds.json
  def index
    @breeds = Breed.all
  end

  # GET /breeds/1
  # GET /breeds/1.json
  def show
  end

  # GET /breeds/new
  def new
    @breed = Breed.new
  end

  # GET /breeds/1/edit
  def edit
  end

  # POST /breeds
  # POST /breeds.json
  def create
    @breed = Breed.new(breed_params)

    respond_to do |format|
      if @breed.save
        format.html { redirect_to @breed, notice: 'Breed was successfully created.' }
        format.json { render :show, status: :created, location: @breed }
      else
        format.html { render :new }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breeds/1
  # PATCH/PUT /breeds/1.json
  def update
    respond_to do |format|
      if @breed.update(breed_params)
        format.html { redirect_to @breed, notice: 'Breed was successfully updated.' }
        format.json { render :show, status: :ok, location: @breed }
      else
        format.html { render :edit }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeds/1
  # DELETE /breeds/1.json
  def destroy
    @breed.destroy
    respond_to do |format|
      format.html { redirect_to breeds_url, notice: 'Breed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breed
      @breed = Breed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breed_params
      params.require(:breed).permit(:name)
    end
end

tp5/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:breed_id, :name)
    end
end

tp5/app/helpers/breeds_helper.rb
module BreedsHelper
end

tp5/app/helpers/pets_helper.rb
module PetsHelper
end

tp5/app/views/application/_navigation.erb
<nav class="navbar navbar-light bg-faded">
  <a href="#" class="navbar-brand">PetsApp</a>
  <div class="nav navbar-nav">
    <%= link_to 'Pets', pets_path, class: 'nav-item nav-link' -%>
    <%= link_to 'Breeds', breeds_path, class: 'nav-item nav-link' -%>
  </div>
</nav>

tp5/app/views/breeds/_form.html.erb
<%= form_for(breed) do |f| %>
  <% if breed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(breed.errors.count, "error") %> prohibited this breed from being saved:</h2>

      <ul>
      <% breed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tp5/app/views/breeds/edit.html.erb
<h1>Editing Breed</h1>

<%= render 'form', breed: @breed %>

<%= link_to 'Show', @breed %> |
<%= link_to 'Back', breeds_path %>

tp5/app/views/breeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breeds.each do |breed| %>
      <tr>
        <td><%= breed.name %></td>
        <td><%= link_to 'Show', breed %></td>
        <td><%= link_to 'Edit', edit_breed_path(breed) %></td>
        <td><%= link_to 'Destroy', breed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breed', new_breed_path %>

tp5/app/views/breeds/new.html.erb
<h1>New Breed</h1>

<%= render 'form', breed: @breed %>

<%= link_to 'Back', breeds_path %>

tp5/app/views/breeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @breed.name %>
</p>

<%= link_to 'Edit', edit_breed_path(@breed) %> |
<%= link_to 'Back', breeds_path %>

tp5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetsApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'navigation' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

tp5/app/views/pets/_form.html.erb
<%= form_for(pet) do |f| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :breed_id %>
    <%= f.text_field :breed_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tp5/app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

tp5/app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Breed</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.breed %></td>
        <td><%= pet.name %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

tp5/app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

tp5/app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>